version: "3.8"

services:
  postgres:
    container_name: paymentdb
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./01-init-database.sql:/docker-entrypoint-initdb.d/01-init-database.sql

volumes:
  pgdata:
